### PR TITLE
Fix inv mod xn

### LINKED ISSUE #519: `test_inv_mod_xn` is flaky
I've seen it fail randomly at least once. I assume the PRNG is to blame.

### PR DESCRIPTION
**Pull request by wborgeaud**
Fix `inv_mod_xn` so that it works on constant polynomials.
Fixes #519.

### CODE REVIEW

File: field/src/polynomial/mod.rs [hunk 1]
```diff
@@ -526,12 +526,17 @@ mod tests {
...
         let n = rng.gen_range(1..1_000);
-        let a = PolynomialCoeffs::new(F::rand_vec(a_deg));
+        let mut a = PolynomialCoeffs::new(F::rand_vec(a_deg + 1));
+        if a.coeffs[0].is_zero() {
+            a.coeffs[0] = F::ONE; // First coefficient needs to be nonzero.
+        }
         let b = a.inv_mod_xn(n);
         let mut m = &a * &b;
-        m.coeffs.drain(n..);
+        if m.coeffs.len() > n {
```
Comment (dlubarov) [inline field/src/polynomial/mod.rs:537]: I think `truncate(n)` would have the same effect

**Review by dlubarov — APPROVED** [review]
